### ISSUE TITLE
HTML report creates empty file

### ISSUE THREAD

**Issue by ghemed** [Dvirus89/tenbisbarcodes#1]
hi, thank you for the script!!!
i can see that the script finds the vouchers but the HTML report is empty

**Comment by Dvirus89** [comment]
![image](https://user-images.githubusercontent.com/1368112/188795751-e3ca9609-4ff4-4bd6-b360-093ac70f3f79.png)
sent by @ghemed directly.
identified as an encoding problem with Windows clients.

**Comment by Dvirus89** [comment]
https://github.com/Dvirus89/tenbisbarcodes/blob/a39f8fb92d37021bab73a9841f503c7aeea15cf2/tenbis-report.py#L101
Fixed by adding utf-8 encoding.
