### ISSUE TITLE
Issue when running the main script

### ISSUE THREAD

**Issue by Nirsisr** [Dvirus89/tenbisbarcodes#4]
Hey, I'm getting the following error after running python3 tenbis-report.py, seems like the script was able to find 2 vouchers, and then at some point, it collapsed.

![image](https://github.com/Dvirus89/tenbisbarcodes/assets/57352006/79799cad-51bb-457e-809a-2182ba26907a)

My email: nir.rashti@nokia.com
10x for your help

**Comment by Dvirus89** [comment]
Hi,
A good start would be changing "DEBUG = False" to "DEBUG = True" and then running and sharing more information.

**Comment by Dvirus89** [comment]
> 

To obtain more accurate information for your situation, you can make a less elegant adjustment by modifying line 182 as follows:
if (not DEBUG):

This will result in fewer irrelevant debug details being displayed.

**Comment by Nirsisr** [comment]
Alright I manipulate line 182 as you suggested and till 10-2022 we only get a successful status code (200).
![image](https://github.com/Dvirus89/tenbisbarcodes/assets/57352006/4b22007f-6493-46b0-b71f-c4b38e7df994)

Error raised with specific bar code 'תקלה בהבאת הברקוד' Data object was returned with empty Vouchers list [] which probably;y cause for the issue since resp_json['Data']['Vouchers'][0] don't exist we got empty list instead.

**Comment by Dvirus89** [comment]
I've pushed a change to handle better this kind of backend error coming from 10Bis.
You can try it.

**Comment by Nirsisr** [comment]
Hey @Dvirus89 I pull all the changes but now it falls on another part.
Adding here a print screen of the case, 10x in advance.
Generally said the tool is really cool, kudos on that !

![image](https://github.com/Dvirus89/tenbisbarcodes/assets/57352006/bad1c869-0172-4921-a99c-a4102fd3d33d)

**Comment by Dvirus89** [comment]
Oh, I've left a test I made and didn't delete it.
I removed it now.
You can try it now if you like.

**Comment by Dvirus89** [comment]
@Nirsisr, I had to remove your comment as it exposed your barcode.

putting it here again (censored):
---
Hey @Dvirus89 I pull all the changes but now it falls on another part.
Adding here a print screen of the case, 10x in advance.
Generally said the tool is really cool, kudos on that !
![image](https://github.com/Dvirus89/tenbisbarcodes/assets/1368112/b201c0f4-60a0-4941-86a5-8e03807e9e24)

---

**Comment by Nirsisr** [comment]
@Dvirus89 the fix work perfectly.
10x, you can close the issue reported.
